# Generated by Django 5.1.15 on 2026-04-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maneuvers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maneuverlog',
            new_name='maneuvers_m_timesta_7ca047_idx',
            old_name='maneuvers_m_timesta_868f7a_idx',
        ),
        migrations.RenameIndex(
            model_name='maneuverlog',
            new_name='maneuvers_m_project_bddc35_idx',
            old_name='maneuvers_m_project_7c752e_idx',
        ),
    ]
