# Generated by Django 5.1.15 on 2026-04-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analogpoint',
            new_name='telemetry_a_telemet_e2b3cc_idx',
            old_name='telemetry_a_telemet_657053_idx',
        ),
        migrations.RenameIndex(
            model_name='binarypoint',
            new_name='telemetry_b_telemet_deb115_idx',
            old_name='telemetry_b_telemet_5f6cb4_idx',
        ),
        migrations.RenameIndex(
            model_name='telemetryrecord',
            new_name='telemetry_t_project_582ace_idx',
            old_name='telemetry_t_project_c15d1f_idx',
        ),
    ]
