# Generated by Django 5.1.15 on 2026-04-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_rename_telemetry_a_telemet_657053_idx_telemetry_a_telemet_e2b3cc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryrecord',
            name='p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='q',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
