# Generated by Django 5.1.15 on 2026-05-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_telemetryrecord_p_telemetryrecord_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryrecord',
            name='high_gas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='high_temperature',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
